export const PRODUCTS = [
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
  {
    image: "/product-1.png",
    name: "Raw Black T-Shirt Lineup",
    sku: "47514501",
    price: 75,
    isInStock: true,
    category: ["T-shirt", "men"],
  },
];
